import { auth } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/src/lib/db";
import { getOrCreateUser, requireUserId } from "@/src/lib/dal";
import { spendCredits } from "@/src/lib/credits";

const DEMO_CONTENT: Record<string, (topic: string) => string> = {
  blog: (topic) => `Title: ${topic} — A Complete Guide for 2025

## Introduction

In today's fast-paced digital landscape, understanding ${topic} has become essential for businesses and professionals alike. Whether you're just getting started or looking to deepen your knowledge, this comprehensive guide covers everything you need to know.

## Why ${topic} Matters

The importance of ${topic} cannot be overstated. Here are the key reasons it matters:

- **Efficiency**: Streamlines your workflow and saves time
- **Scalability**: Grows with your business needs
- **ROI**: Delivers measurable results

## Getting Started

### Step 1: Define Your Goals

Before diving into ${topic}, it's crucial to establish clear objectives. Ask yourself:

1. What outcomes do you want to achieve?
2. What resources do you have available?
3. What timeline are you working with?

### Step 2: Build Your Foundation

Start with the fundamentals. Focus on:

- Understanding core principles
- Learning best practices
- Studying successful examples

### Step 3: Implement and Iterate

Put your plan into action. Remember:

- Start small and scale gradually
- Measure results consistently
- Adjust based on data

## Best Practices

Here are proven strategies for success with ${topic}:

1. **Be Consistent**: Regular effort beats sporadic bursts
2. **Stay Data-Driven**: Let metrics guide your decisions
3. **Keep Learning**: The landscape evolves — stay current
4. **Collaborate**: Leverage team expertise and insights

## Common Mistakes to Avoid

- Skipping the research phase
- Setting unrealistic expectations
- Ignoring feedback from your audience
- Failing to track and measure results

## Conclusion

${topic} is a powerful tool when used correctly. By following this guide, you'll be well on your way to achieving your goals. Start implementing these strategies today and watch your results improve.

---
*This content was generated by ContentForge AI — free unlimited content generation.*`,

  social: (topic) => `📱 Social Media Post — ${topic}

Stop scrolling. Start creating. 🚀

Here's the truth about ${topic}:

Most people overcomplicate it. The secret? Start simple, stay consistent, and let results guide you.

Here are 5 quick wins you can try today:

✅ Focus on your audience first, not yourself
✅ Create content that educates or entertains
✅ Use data to double down on what works
✅ Engage with your community daily
✅ Test new formats without fear of failure

The brands winning at ${topic} right now aren't doing anything magic — they're just being intentional.

💬 What's your biggest challenge with ${topic}? Drop it below 👇

#ContentMarketing #DigitalStrategy #GrowthHacking #MarketingTips #ContentCreation #BusinessGrowth`,

  email: (topic) => `Subject: Quick tip to improve your ${topic} today

Hi there,

I wanted to share something that could make a real difference in how you approach ${topic}.

Here's the thing — most people think they need a massive budget or a huge team to see results. But the reality is that small, consistent improvements compound into big wins.

Here's what I recommend:

1. Start with an audit of your current approach
2. Identify one area where you can make an immediate improvement
3. Set a 30-day goal to measure the impact
4. Double down on what works

I've seen this simple framework help teams increase their output by 3x in just a few months.

Want to see how it works? Reply to this email and I'll share a free template that makes it easy.

Best,
The ContentForge Team

P.S. Everything is free — no credit card required. Start generating content now.`,

  ad: (topic) => `🎯 Headline: Transform Your ${topic} — Start Free Today

副标题: Join 2,000+ teams already seeing results

BODY COPY:

Tired of spending hours on ${topic} with little to show for it?

ContentForge makes it simple. Our AI-powered platform generates high-quality content in seconds — blog posts, social media, emails, and more.

Here's what you get:
→ 7 content types at your fingertips
→ Publication-ready content in seconds
→ Templates to speed up your workflow
→ Analytics to track your progress

No credit card. No limits. Just results.

CTA: Get Started Free →

SOCIAL PROOF:
"ContentForge cut our content production time by 70%." — Sarah Chen, Marketing Director

TESTIMONIAL BADGE: ⭐⭐⭐⭐⭐ Rated 4.9/5 by 2,000+ agencies`,

  website: (topic) => `# Hero Section

## ${topic} — Made Simple

Generate professional content in seconds with AI. No writing skills required.

**Get Started Free →**

---

# Features Section

## Everything You Need for ${topic}

### AI-Powered Writing
Our advanced AI understands your brand voice and generates content that sounds like you wrote it — just faster.

### 7 Content Types
From blog posts to ad copy, emails to product descriptions — we've got every format covered.

### Templates Library
Start with proven templates. Customize, iterate, and publish in minutes, not hours.

### Analytics Dashboard
Track your content performance. See what works, what doesn't, and optimize your strategy.

---

# CTA Section

## Ready to Transform Your ${topic}?

Join thousands of teams using ContentForge to produce high-quality content at scale.

**[Start Free — No Card Required]**

---

# Testimonials

"ContentForge has cut our content production time by 70%."
— Sarah Chen, Marketing Director at TechFlow

"We manage content for 15+ clients. ContentForge lets us scale."
— Marcus Rivera, Agency Owner at GrowthLab`,

  product: (topic) => `# ${topic} — Product Description

## Overview

Discover the power of ${topic} with our comprehensive solution designed for modern teams. Whether you're a startup or an enterprise, our platform adapts to your needs.

## Key Features

- **Intelligent Automation**: Streamline repetitive tasks and focus on what matters
- **Real-Time Analytics**: Make data-driven decisions with instant insights
- **Seamless Integration**: Works with your existing tools and workflows
- **Scalable Architecture**: Grows with your business, from 1 to 10,000 users
- **Enterprise Security**: SOC 2 compliant with end-to-end encryption

## What's Included

✅ Full platform access with no restrictions
✅ Priority email support
✅ Regular feature updates
✅ Community access and resources
✅ API access for custom integrations

## Who It's For

- Marketing teams looking to scale content production
- Agencies managing multiple client accounts
- Freelancers who want to work faster
- Startups building their brand presence

## Why Choose Us

Unlike traditional solutions, our platform combines cutting-edge AI with an intuitive interface. You don't need to be a tech expert to get professional results.

## Pricing

Everything is free. No credit card required. No limits on usage.

**[Get Started Now]**`,

  seo: (topic) => `Title: ${topic} — Complete Guide [2025 Updated]
Meta Description: Learn everything about ${topic} in this comprehensive guide. Tips, strategies, and best practices for beginners and experts alike.
Focus Keyword: ${topic}

---

# ${topic}: The Ultimate Guide

## SEO Outline

### H2: What is ${topic}?
${topic} refers to the practice of... [Define the concept clearly for readers and search engines]

### H2: Why is ${topic} Important?
- Improves visibility and reach
- Drives organic traffic
- Builds authority and trust

### H2: How to Get Started with ${topic}
1. Research your target audience
2. Create a content strategy
3. Optimize for search engines
4. Measure and iterate

### H2: Best Practices for ${topic}
- Use long-tail keywords naturally
- Focus on user intent
- Create comprehensive, valuable content
- Build internal linking structures

### H2: Common Mistakes to Avoid
- Keyword stuffing
- Ignoring mobile optimization
- Publishing without proper formatting
- Neglecting analytics

### H2: Tools and Resources
- Google Analytics for tracking
- SEMrush for keyword research
- Ahrefs for backlink analysis
- Yoast SEO for on-page optimization

### H2: Frequently Asked Questions

**Q: How long does it take to see results from ${topic}?**
A: Typically 3-6 months for significant results, though quick wins can happen sooner.

**Q: What budget do I need for ${topic}?**
A: You can start with minimal investment. Focus on time and consistency first.

**Q: Can I do ${topic} myself?**
A: Absolutely. Many professionals handle it in-house with the right tools and knowledge.

---

*Content optimized for SEO by ContentForge AI*`,
};

const GenerateRequestSchema = z.object({
  type: z.enum(["blog", "social", "email", "ad", "website", "product", "seo"]).default("blog"),
  prompt: z.string().min(1, "Prompt is required").max(10000, "Prompt is too long"),
});

export const runtime = "nodejs";
export const maxDuration = 30;

export async function POST(req: Request) {
  try {
    const { userId: rawUserId } = await auth();
    const userId = requireUserId(rawUserId);

    const body = await req.json();
    const parsed = GenerateRequestSchema.safeParse(body);

    if (!parsed.success) {
      return NextResponse.json(
        { error: parsed.error.issues[0]?.message ?? "Invalid request" },
        { status: 400 }
      );
    }

    const { type, prompt } = parsed.data;
    const user = await getOrCreateUser(userId);

    if (user.credits < 1) {
      return NextResponse.json(
        { error: "Insufficient credits" },
        { status: 402 }
      );
    }

    const hasOpenAI = process.env.OPENAI_API_KEY && !process.env.OPENAI_API_KEY.includes("placeholder");

    let content: string;

    if (hasOpenAI) {
      const OpenAI = (await import("openai")).default;
      const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
      const instructions = `You are an expert content marketer. Write high-quality content about the topic provided. Be professional, engaging, and thorough.`;
      const response = await openai.responses.create({
        model: process.env.OPENAI_MODEL ?? "gpt-4o-mini",
        instructions,
        input: prompt,
      });
      content = response.output_text;
    } else {
      const generator = DEMO_CONTENT[type] ?? DEMO_CONTENT.blog;
      content = generator(prompt);
    }

    const title = extractTitle(content) || prompt.slice(0, 60);
    const generation = await db.generation.create({
      data: {
        userId: user.id,
        type,
        title,
        content,
        prompt,
        creditsUsed: 1,
      },
    });

    await spendCredits(userId, 1);

    return NextResponse.json({
      content,
      type,
      title,
      id: generation.id,
    });
  } catch (error: unknown) {
    console.error("Generate error:", error);
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

function extractTitle(content: string): string | null {
  const titleMatch = content.match(/^Title:\s*(.+)$/m);
  if (titleMatch) return titleMatch[1].trim();
  const firstLine = content.split("\n").find((l) => l.trim());
  return firstLine ? firstLine.trim().slice(0, 100) : null;
}
